# Docker-compose is a way to run multiple containers at once and connect them
# This sets up and runs postgres and the django dev server as services
# Reference: https://docs.docker.com/compose/compose-file/

# Initial setup with
# $ docker-compose -f docker-compose.yml up

# Can run management commands with
# $ docker-compose run web /code/manage.py whatever

version: '3'

services:
  web:
    build: .
    command: ["./bin/docker-run-honcho.sh"]
    expose:
      - "8000"
    environment:
      - DEBUG=1
      - IN_DOCKER=1
      - DISABLE_SENTRY=1
      - USING_NGINX=1
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./tabbycat/settings:/tcd/tabbycat/settings
    working_dir: /tcd

  worker:
    build: .
    command: ["./bin/docker-run-worker.sh"]
    environment:
      - DEBUG=1
      - IN_DOCKER=1
      - DISABLE_SENTRY=1
      - USING_NGINX=1
    volumes:
      - ./tabbycat/settings:/tcd/tabbycat/settings
    working_dir: /tcd

