# Generated by Django 2.0.2 on 2018-02-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]
    
    operations = [
        migrations.RunSQL(
            sql=[
                """
                MERGE INTO options_tournamentpreferencemodel AS target
                USING (
                    SELECT id AS instance_id, 'public_features' AS section, 'welcome_message' AS name, welcome_msg AS raw_value
                    FROM tournaments_tournament
                ) AS source
                ON (target.instance_id = source.instance_id AND target.section = source.section AND target.name = source.name)
                WHEN MATCHED THEN
                    UPDATE SET target.raw_value = source.raw_value
                WHEN NOT MATCHED THEN
                    INSERT (section, name, raw_value, instance_id)
                    VALUES (source.section, source.name, source.raw_value, source.instance_id);
                """,
                """
                UPDATE t
                SET t.welcome_msg = o.raw_value
                FROM tournaments_tournament t
                INNER JOIN options_tournamentpreferencemodel o ON t.id = o.instance_id
                WHERE o.section = 'public_features' AND o.name = 'welcome_message';
                """
            ],
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        ),
    ]
