# Generated by Django 2.0.8 on 2018-09-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0004_add_teaminstitutionconflict'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            MERGE INTO adjallocation_teaminstitutionconflict AS target
            USING (
                SELECT id AS team_id, institution_id
                FROM participants_team
                WHERE institution_id IS NOT NULL
            ) AS source
            ON (target.team_id = source.team_id AND target.institution_id = source.institution_id)
            WHEN NOT MATCHED THEN
                INSERT (team_id, institution_id)
                VALUES (source.team_id, source.institution_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        ),
    ]
