# Generated by Django 2.2.9 on 2020-06-13 12:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_remove_league_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='flags_temp',
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE draw_debate
                SET flags_temp = (
                    SELECT STRING_AGG(value, ',')
                    FROM STRING_SPLIT(flags, ',')
                );
            """,
            reverse_sql="""
                UPDATE draw_debate
                SET flags = (
                    SELECT STRING_AGG(value, ',')
                    FROM OPENJSON(flags_temp)
                    WITH (value NVARCHAR(MAX) '$')
                );
            """,
        ),
        migrations.RemoveField(
            model_name='debate',
            name='flags',
        ),
        migrations.RenameField(
            model_name='debate',
            old_name='flags_temp',
            new_name='flags',
        ),
        migrations.AddField(
            model_name='debateteam',
            name='flags_temp',
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE draw_debateteam
                SET flags_temp = (
                    SELECT STRING_AGG(value, ',')
                    FROM STRING_SPLIT(flags, ',')
                );
            """,
            reverse_sql="""
                UPDATE draw_debateteam
                SET flags = (
                    SELECT STRING_AGG(value, ',')
                    FROM OPENJSON(flags_temp)
                    WITH (value NVARCHAR(MAX) '$')
                );
            """,
        ),
        migrations.RemoveField(
            model_name='debateteam',
            name='flags'
        ),
        migrations.RenameField(
            model_name='debateteam',
            old_name='flags_temp',
            new_name='flags'
        ),
    ]
