# Generated by Django 3.1.1 on 2020-10-03 09:05

from django.db import migrations, models
import utils.fields

class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0006_merge_20200904_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE draw_debate
                SET flags = (
                    SELECT STRING_AGG(value, ',')
                    FROM STRING_SPLIT(flags, ',')
                );
            """,
            reverse_sql="""
                UPDATE draw_debate
                SET flags = (
                    SELECT STRING_AGG(value, ',')
                    FROM OPENJSON(flags)
                    WITH (value NVARCHAR(MAX) '$')
                );
            """,
        ),
        migrations.AlterField(
            model_name='debateteam',
            name='flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE draw_debateteam
                SET flags = (
                    SELECT STRING_AGG(value, ',')
                    FROM STRING_SPLIT(flags, ',')
                );
            """,
            reverse_sql="""
                UPDATE draw_debateteam
                SET flags = (
                    SELECT STRING_AGG(value, ',')
                    FROM OPENJSON(flags)
                    WITH (value NVARCHAR(MAX) '$')
                );
            """,
        ),
    ]
