# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - plerdtabby

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      ## Environment variable
      GITHUB_CI: true

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-node-

    - name: Cache pipenv modules
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system --dev --deploy
        npm ci

    - name: Run build and collect static files
      run: |
        npm run build
        python ./tabbycat/manage.py collectstatic --noinput -v 0
        
    - name: Zip the package
      run: |
        zip -r myapp.zip .
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp
        path: myapp.zip

  build-docker-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build Docker image (dev)
        run: docker-compose -f docker-compose.yml build

  build-docker-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build Docker image (prod)
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

  deploy:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-docker-dev, build-docker-prod]

    steps:
      - uses: actions/checkout@v3
    
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myapp
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies with pipenv
        run: |
          pipenv install --system --dev --deploy
         
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'plerdtabby'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_60E5B3E05D4949B4AFC0C534C5F32AD3 }}
          package: ./myapp.zip
        env:
          AZURE_HTTP_USER_AGENT: 'GITHUBACTIONS_${{ github.workflow }}_${{ github.run_id }}'
